### ISSUE TITLE
docs site is down 

### ISSUE THREAD

**Issue by dogfrogfog** [sb-mig/sb-mig#296]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marckraw** [comment]
hey @dogfrogfog 

the docs are just in `readme.md` file actually :) will remove link to the site - had no time to maintain it, so all that is about sb-mig is in the repo and markdown files :)

**Comment by marckraw** [comment]
related pr: https://github.com/sb-mig/sb-mig/pull/298
