### ISSUE TITLE
docs site is down https://docs.sb-mig.com/

### ISSUE THREAD

**Issue by dogfrogfog** [sb-mig/sb-mig#297]
![Screenshot 2024-10-23 at 07 59 47](https://github.com/user-attachments/assets/22970b48-6cb8-4a7a-8c21-8d2018339d48)

**Comment by marckraw** [comment]
hey @dogfrogfog 

the docs are just in `readme.md` file actually :) will remove link to the site - had no time to maintain it, so all that is about sb-mig is in the repo and markdown files :)
