### ISSUE TITLE
Add ability to use sb-mig programmatically

### ISSUE THREAD

**Issue by hjaimee** [sb-mig/sb-mig#53]
Would be great if we could use sb-mig programmatically by instantiating the object and be able to use exposed methods.

This would provide more flexibility to able to implement a custom component deployment flow in a script file, handle error cases with retry, and support many other desired cases.

**Comment by marckraw** [comment]
Thanks for the input @hjaimee ! That sounds dope, but could be not that easy to implement. Let's start conversatoion about that and link any tries/PR to handle that thing to this issue 👍  

Do you have any proposal, how it would look like in some random case ? In pseudo code, just for  being on the same page about this idea 🙂

**Comment by marckraw** [comment]
Note to self: check if this is still an issue. It should be possibly now to use `sb-mig` base oclif class, to use it programatically.
