### ISSUE TITLE
Add ability for sb-mig to remove unused schema from Storyblok

### ISSUE THREAD

**Issue by dat-william** [sb-mig/sb-mig#56]
There is currently no command to move a singular schema from storyblok once migrated the schemas from earlier on.

The method `--syncAll` only migrated all schemas but did not remove any unused ones as well.

**Comment by marckraw** [comment]
Idea would be to add, flag for it, to say that local schemas are single source of truth, so when it will sync all components, it will also remove ones added in GUI. But it is highly risku feature, so it has to be behind a flag. 

Other option is to add command, which will remove specific components.

**Comment by marckraw** [comment]
There are two new issues created for it:
- https://github.com/sb-mig/sb-mig/issues/112 - flag to remove unused schemas
- https://github.com/sb-mig/sb-mig/issues/113 - flag for syncing components, which will sync them as exact copy

**Comment by marckraw** [comment]
This feature (behind flag) will be hopefully implemented in **v5**.

**Comment by marckraw** [comment]
So this one, is actually release with beta via this commit: https://github.com/sb-mig/sb-mig/commit/a1f7b05f0d8f716ba990035dc32dab8dd684b63f

We can sync components and treating our code as single source of truth (it will remove all storyblok components that are existing in GUI but not existing in code)
```
sb-mig sync components --all --ssot
```

We can also utilize NEW remove command to remove specified components
```
sb-mig remove components accordion blockquote
```
it will remove 2 components from storyblok.
